// Code generated by MockGen. DO NOT EDIT.
// Source: account.go

// Package repoiface is a generated GoMock package.
package repoiface

import (
	context "context"
	reflect "reflect"

	models "github.com/IsaacIsRebooting/Metok/backend/basesvr/internal/data/dal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAccountRepo is a mock of AccountRepo interface.
type MockAccountRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepoMockRecorder
}

// MockAccountRepoMockRecorder is the mock recorder for MockAccountRepo.
type MockAccountRepoMockRecorder struct {
	mock *MockAccountRepo
}

// NewMockAccountRepo creates a new mock instance.
func NewMockAccountRepo(ctrl *gomock.Controller) *MockAccountRepo {
	mock := &MockAccountRepo{ctrl: ctrl}
	mock.recorder = &MockAccountRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepo) EXPECT() *MockAccountRepoMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockAccountRepo) CreateAccount(ctx context.Context, account *models.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountRepoMockRecorder) CreateAccount(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccountRepo)(nil).CreateAccount), ctx, account)
}

// GetAccountByEmail mocks base method.
func (m *MockAccountRepo) GetAccountByEmail(ctx context.Context, email string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByEmail", ctx, email)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByEmail indicates an expected call of GetAccountByEmail.
func (mr *MockAccountRepoMockRecorder) GetAccountByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByEmail", reflect.TypeOf((*MockAccountRepo)(nil).GetAccountByEmail), ctx, email)
}

// GetAccountById mocks base method.
func (m *MockAccountRepo) GetAccountById(ctx context.Context, id int64) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountById", ctx, id)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountById indicates an expected call of GetAccountById.
func (mr *MockAccountRepoMockRecorder) GetAccountById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountById", reflect.TypeOf((*MockAccountRepo)(nil).GetAccountById), ctx, id)
}

// GetAccountByMobile mocks base method.
func (m *MockAccountRepo) GetAccountByMobile(ctx context.Context, mobile string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByMobile", ctx, mobile)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByMobile indicates an expected call of GetAccountByMobile.
func (mr *MockAccountRepoMockRecorder) GetAccountByMobile(ctx, mobile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByMobile", reflect.TypeOf((*MockAccountRepo)(nil).GetAccountByMobile), ctx, mobile)
}

// IsEmailExist mocks base method.
func (m *MockAccountRepo) IsEmailExist(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmailExist", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEmailExist indicates an expected call of IsEmailExist.
func (mr *MockAccountRepoMockRecorder) IsEmailExist(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmailExist", reflect.TypeOf((*MockAccountRepo)(nil).IsEmailExist), ctx, email)
}

// IsMobileExist mocks base method.
func (m *MockAccountRepo) IsMobileExist(ctx context.Context, mobile string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMobileExist", ctx, mobile)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMobileExist indicates an expected call of IsMobileExist.
func (mr *MockAccountRepoMockRecorder) IsMobileExist(ctx, mobile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMobileExist", reflect.TypeOf((*MockAccountRepo)(nil).IsMobileExist), ctx, mobile)
}

// ModifyPassword mocks base method.
func (m *MockAccountRepo) ModifyPassword(ctx context.Context, account *models.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyPassword", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyPassword indicates an expected call of ModifyPassword.
func (mr *MockAccountRepoMockRecorder) ModifyPassword(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyPassword", reflect.TypeOf((*MockAccountRepo)(nil).ModifyPassword), ctx, account)
}
