version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: base_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zl020613
      MYSQL_DATABASE: base_db
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: metok_redis
    command: ["redis-server", "--requirepass", "root"]
    ports:
      - "6379:6379"

  etcd:
    image: bitnami/etcd:latest
    container_name: metok_etcd
    ports:
      - "2479:2379"
      - "2480:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379


  minio:
    image: minio/minio:latest
    container_name: metok_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootroot
    command: server /data --console-address ":9001"

  consul:
    image: consul:latest
    container_name: metok_consul
    ports:
      - "8500:8500"
    command: consul agent -dev -client=0.0.0.0

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: metok_jaeger
    ports:
      - "14268:14268"
      - "16686:16686"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

volumes:
  mysql_data:
    driver: local