syntax = "proto3";
package kratos.api;

option go_package = "basesvr/internal/conf;conf";


message Config {
  Base base = 1;
  Server server = 2;
  Data data = 3;
  Snowflake snowflake = 4;
}

message Base {
  string app_id = 1;
  string app_name = 2;
  string version = 3;
}

message Data {
  Database database = 1;
  Redis redis = 2;
  Minio minio = 3;
  map<string, DbShardingConfig> db_sharding_config = 4;
  map<string, DomainShardingConfig> db_sharding_tables = 5;
}
// 数据库配置
message Database {
  string source = 1;
}

// Redis 配置
message Redis {
  string source = 1;
  string password = 2;
}

// Minio 配置
message Minio {
  string endpoint = 1;
  string access_key = 2;
  string secret_key = 3;
}

// 数据库分片配置
message DbShardingConfig {
  string sharding = 1;
  int64 sharding_number = 2;
}

// 分片表配置
message ShardingNumberConfig {
  string table_name = 1;
  string domain_name = 2;
  string biz_name = 3;
  int64 sharding_number = 4;
}

// 业务分片字段配置
message BizShardingFieldConfig {
  repeated string fields = 1;
}

// 域分片配置
message DomainShardingConfig {
  string domain_name = 1;
  map<string, BizShardingFieldConfig> biz_sharding_field_config = 2;
}

// 服务配置
message Server {
  Grpc grpc = 1;
}

// gRPC 服务配置
message Grpc {
  string addr = 1;
}

// 雪花算法配置
message Snowflake {
  int64 node = 1;
}
