// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAccount = "account"

// Account mapped from table <account>
type Account struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Mobile     string    `gorm:"column:mobile;type:varchar(20);not null;uniqueIndex:mobile,priority:1;index:account_mobile_idx,priority:1" json:"mobile"`
	Email      string    `gorm:"column:email;type:varchar(100);not null;uniqueIndex:email,priority:1;index:account_email_idx,priority:1" json:"email"`
	Password   string    `gorm:"column:password;type:varchar(64);not null" json:"password"`
	Salt       string    `gorm:"column:salt;type:varchar(64);not null" json:"salt"`
	IsDeleted  bool      `gorm:"column:is_deleted;type:tinyint(1);not null" json:"is_deleted"`
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	TokNumber  string    `gorm:"column:tok_number;type:varchar(15);not null;comment:Metok号" json:"tok_number"` // Metok号
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
