/* Generated by restful-react */

import React from "react";
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from "restful-react";
export const SPEC_VERSION = "0.0.1"; 
export interface SvapiBindUserVoucherRequest {
  voucherType?: number;
  voucher?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiBindUserVoucherResponse {}

export interface SvapiGetUserInfoResponse {
  user?: SvapiUser;
}

export interface SvapiGetVerificationCodeRequest {
  mobile?: string;
  email?: string;
}

export interface SvapiGetVerificationCodeResponse {
  /**
   * @gotags: json:"code_id,omitempty,string"
   */
  codeId?: string;
}

export interface SvapiLoginRequest {
  mobile?: string;
  email?: string;
  password?: string;
}

export interface SvapiLoginResponse {
  token?: string;
}

export interface SvapiRegisterRequest {
  mobile?: string;
  email?: string;
  password?: string;
  /**
   * @gotags: json:"code_id,omitempty,string"
   */
  codeId?: string;
  code?: string;
}

export interface SvapiRegisterResponse {
  /**
   * @gotags: json:"user_id,omitempty,string"
   */
  userId?: string;
}

export interface SvapiUnbindUserVoucherRequest {
  voucherType?: number;
  voucher?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiUnbindUserVoucherResponse {}

export interface SvapiUpdateUserInfoRequest {
  /**
   * @gotags: json:"user_id,omitempty,string"
   */
  userId?: string;
  name?: string;
  avatar?: string;
  backgroundImage?: string;
  signature?: string;
}

// tslint:disable-next-line:no-empty-interface
export interface SvapiUpdateUserInfoResponse {}

export interface SvapiUser {
  /**
   * @gotags: json:"id,omitempty,string"
   */
  id?: string;
  name?: string;
  avatar?: string;
  backgroundImage?: string;
  signature?: string;
  mobile?: string;
  email?: string;
  /**
   * @gotags: json:"followCount,omitempty,string"
   */
  followCount?: string;
  /**
   * @gotags: json:"followerCount,omitempty,string"
   */
  followerCount?: string;
  /**
   * @gotags: json:"totalFavorited,omitempty,string"
   */
  totalFavorited?: string;
  /**
   * @gotags: json:"workCount,omitempty,string"
   */
  workCount?: string;
  /**
   * @gotags: json:"favoriteCount,omitempty,string"
   */
  favoriteCount?: string;
}

export type UserServiceGetVerificationCodeProps = Omit<MutateProps<SvapiGetVerificationCodeResponse, unknown, void, SvapiGetVerificationCodeRequest, void>, "path" | "verb">;

/**
 * 获取验证码
 */
export const UserServiceGetVerificationCode = (props: UserServiceGetVerificationCodeProps) => (
  <Mutate<SvapiGetVerificationCodeResponse, unknown, void, SvapiGetVerificationCodeRequest, void>
    verb="POST"
    path={`/user/code`}
    
    {...props}
  />
);

export type UseUserServiceGetVerificationCodeProps = Omit<UseMutateProps<SvapiGetVerificationCodeResponse, unknown, void, SvapiGetVerificationCodeRequest, void>, "path" | "verb">;

/**
 * 获取验证码
 */
export const useUserServiceGetVerificationCode = (props: UseUserServiceGetVerificationCodeProps) => useMutate<SvapiGetVerificationCodeResponse, unknown, void, SvapiGetVerificationCodeRequest, void>("POST", `/user/code`, props);


export interface UserServiceGetUserInfoQueryParams {
  /**
   * @gotags: json:"user_id,omitempty,string"
   */
  userId?: string;
}

export type UserServiceGetUserInfoProps = Omit<GetProps<SvapiGetUserInfoResponse, unknown, UserServiceGetUserInfoQueryParams, void>, "path">;

/**
 * 获取用户信息
 */
export const UserServiceGetUserInfo = (props: UserServiceGetUserInfoProps) => (
  <Get<SvapiGetUserInfoResponse, unknown, UserServiceGetUserInfoQueryParams, void>
    path={`/user/info`}
    
    {...props}
  />
);

export type UseUserServiceGetUserInfoProps = Omit<UseGetProps<SvapiGetUserInfoResponse, unknown, UserServiceGetUserInfoQueryParams, void>, "path">;

/**
 * 获取用户信息
 */
export const useUserServiceGetUserInfo = (props: UseUserServiceGetUserInfoProps) => useGet<SvapiGetUserInfoResponse, unknown, UserServiceGetUserInfoQueryParams, void>(`/user/info`, props);


export type UserServiceUpdateUserInfoProps = Omit<MutateProps<SvapiUpdateUserInfoResponse, unknown, void, SvapiUpdateUserInfoRequest, void>, "path" | "verb">;

/**
 * 更新用户信息
 */
export const UserServiceUpdateUserInfo = (props: UserServiceUpdateUserInfoProps) => (
  <Mutate<SvapiUpdateUserInfoResponse, unknown, void, SvapiUpdateUserInfoRequest, void>
    verb="PUT"
    path={`/user/info`}
    
    {...props}
  />
);

export type UseUserServiceUpdateUserInfoProps = Omit<UseMutateProps<SvapiUpdateUserInfoResponse, unknown, void, SvapiUpdateUserInfoRequest, void>, "path" | "verb">;

/**
 * 更新用户信息
 */
export const useUserServiceUpdateUserInfo = (props: UseUserServiceUpdateUserInfoProps) => useMutate<SvapiUpdateUserInfoResponse, unknown, void, SvapiUpdateUserInfoRequest, void>("PUT", `/user/info`, props);


export type UserServiceLoginProps = Omit<MutateProps<SvapiLoginResponse, unknown, void, SvapiLoginRequest, void>, "path" | "verb">;

/**
 * 登录
 */
export const UserServiceLogin = (props: UserServiceLoginProps) => (
  <Mutate<SvapiLoginResponse, unknown, void, SvapiLoginRequest, void>
    verb="POST"
    path={`/user/login`}
    
    {...props}
  />
);

export type UseUserServiceLoginProps = Omit<UseMutateProps<SvapiLoginResponse, unknown, void, SvapiLoginRequest, void>, "path" | "verb">;

/**
 * 登录
 */
export const useUserServiceLogin = (props: UseUserServiceLoginProps) => useMutate<SvapiLoginResponse, unknown, void, SvapiLoginRequest, void>("POST", `/user/login`, props);


export type UserServiceRegisterProps = Omit<MutateProps<SvapiRegisterResponse, unknown, void, SvapiRegisterRequest, void>, "path" | "verb">;

/**
 * 注册
 */
export const UserServiceRegister = (props: UserServiceRegisterProps) => (
  <Mutate<SvapiRegisterResponse, unknown, void, SvapiRegisterRequest, void>
    verb="POST"
    path={`/user/register`}
    
    {...props}
  />
);

export type UseUserServiceRegisterProps = Omit<UseMutateProps<SvapiRegisterResponse, unknown, void, SvapiRegisterRequest, void>, "path" | "verb">;

/**
 * 注册
 */
export const useUserServiceRegister = (props: UseUserServiceRegisterProps) => useMutate<SvapiRegisterResponse, unknown, void, SvapiRegisterRequest, void>("POST", `/user/register`, props);


export type UserServiceBindUserVoucherProps = Omit<MutateProps<SvapiBindUserVoucherResponse, unknown, void, SvapiBindUserVoucherRequest, void>, "path" | "verb">;

export const UserServiceBindUserVoucher = (props: UserServiceBindUserVoucherProps) => (
  <Mutate<SvapiBindUserVoucherResponse, unknown, void, SvapiBindUserVoucherRequest, void>
    verb="POST"
    path={`/user/voucher`}
    
    {...props}
  />
);

export type UseUserServiceBindUserVoucherProps = Omit<UseMutateProps<SvapiBindUserVoucherResponse, unknown, void, SvapiBindUserVoucherRequest, void>, "path" | "verb">;

export const useUserServiceBindUserVoucher = (props: UseUserServiceBindUserVoucherProps) => useMutate<SvapiBindUserVoucherResponse, unknown, void, SvapiBindUserVoucherRequest, void>("POST", `/user/voucher`, props);


export type UserServiceUnbindUserVoucherProps = Omit<MutateProps<SvapiUnbindUserVoucherResponse, unknown, void, SvapiUnbindUserVoucherRequest, void>, "path" | "verb">;

export const UserServiceUnbindUserVoucher = (props: UserServiceUnbindUserVoucherProps) => (
  <Mutate<SvapiUnbindUserVoucherResponse, unknown, void, SvapiUnbindUserVoucherRequest, void>
    verb="DELETE"
    path={`/user/voucher`}
    
    {...props}
  />
);

export type UseUserServiceUnbindUserVoucherProps = Omit<UseMutateProps<SvapiUnbindUserVoucherResponse, unknown, void, SvapiUnbindUserVoucherRequest, void>, "path" | "verb">;

export const useUserServiceUnbindUserVoucher = (props: UseUserServiceUnbindUserVoucherProps) => useMutate<SvapiUnbindUserVoucherResponse, unknown, void, SvapiUnbindUserVoucherRequest, void>("DELETE", `/user/voucher`, {   ...props });

