// Code generated by MockGen. DO NOT EDIT.
// Source: account.go

// Package svciface is a generated GoMock package.
package svciface

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountUseCase is a mock of AccountUseCase interface.
type MockAccountUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAccountUseCaseMockRecorder
}

// MockAccountUseCaseMockRecorder is the mock recorder for MockAccountUseCase.
type MockAccountUseCaseMockRecorder struct {
	mock *MockAccountUseCase
}

// NewMockAccountUseCase creates a new mock instance.
func NewMockAccountUseCase(ctrl *gomock.Controller) *MockAccountUseCase {
	mock := &MockAccountUseCase{ctrl: ctrl}
	mock.recorder = &MockAccountUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountUseCase) EXPECT() *MockAccountUseCaseMockRecorder {
	return m.recorder
}

// CheckPasswordByEmail mocks base method.
func (m *MockAccountUseCase) CheckPasswordByEmail(ctx context.Context, email, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPasswordByEmail", ctx, email, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPasswordByEmail indicates an expected call of CheckPasswordByEmail.
func (mr *MockAccountUseCaseMockRecorder) CheckPasswordByEmail(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPasswordByEmail", reflect.TypeOf((*MockAccountUseCase)(nil).CheckPasswordByEmail), ctx, email, password)
}

// CheckPasswordById mocks base method.
func (m *MockAccountUseCase) CheckPasswordById(ctx context.Context, id int64, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPasswordById", ctx, id, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPasswordById indicates an expected call of CheckPasswordById.
func (mr *MockAccountUseCaseMockRecorder) CheckPasswordById(ctx, id, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPasswordById", reflect.TypeOf((*MockAccountUseCase)(nil).CheckPasswordById), ctx, id, password)
}

// CheckPasswordByMobile mocks base method.
func (m *MockAccountUseCase) CheckPasswordByMobile(ctx context.Context, mobile, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPasswordByMobile", ctx, mobile, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPasswordByMobile indicates an expected call of CheckPasswordByMobile.
func (mr *MockAccountUseCaseMockRecorder) CheckPasswordByMobile(ctx, mobile, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPasswordByMobile", reflect.TypeOf((*MockAccountUseCase)(nil).CheckPasswordByMobile), ctx, mobile, password)
}

// Create mocks base method.
func (m *MockAccountUseCase) Create(ctx context.Context, mobile, email, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, mobile, email, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountUseCaseMockRecorder) Create(ctx, mobile, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountUseCase)(nil).Create), ctx, mobile, email, password)
}

// ModifyPassword mocks base method.
func (m *MockAccountUseCase) ModifyPassword(ctx context.Context, id int64, oldPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyPassword", ctx, id, oldPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyPassword indicates an expected call of ModifyPassword.
func (mr *MockAccountUseCaseMockRecorder) ModifyPassword(ctx, id, oldPassword, newPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyPassword", reflect.TypeOf((*MockAccountUseCase)(nil).ModifyPassword), ctx, id, oldPassword, newPassword)
}
