// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/IsaacIsRebooting/Metok/backend/basesvr/internal/biz"
	"github.com/IsaacIsRebooting/Metok/backend/basesvr/internal/data/repostories/accountrepo"
	"github.com/IsaacIsRebooting/Metok/backend/basesvr/internal/service"
)

// Injectors from wire.go:
func initAccountApplication() *service.AccountService {
	persistRepository := accountrepo.NewPersistRepository()
	accountUseCase := biz.NewAccountUseCase(persistRepository)
	accountService := service.NewAccountService(accountUseCase)
	return accountService
}
